import { useEffect, useMemo, useState } from 'react'
import { ScaleIcon } from '../../components/icons/Lucide'
import { formatJurisdiction, formatPosition } from '../../components/module1/positionConfig'
import { initialsFor, KpiGrid, PaginationMini, StatusLine, TimelineLedger } from '../pageHelpers'

function ComparisonGrid({ comparison }) { const rows = comparison.alignedHorizontalMatrix || []; return <div className="comparisonGrid"><CandidateColumn profile={comparison.profileA} /><CandidateColumn profile={comparison.profileB} /><section className="matrix"><h2 className="ty-section-title">Aligned Evidence Ledger</h2>{rows.map((row) => <div className="matrixRow" key={row.categoryTag}><h3>{row.categoryTag}</h3><div className="compareLedgerPair"><TimelineLedger className="comparisonLedgerCard" entries={row.recordsA || []} title="Candidate A" /><TimelineLedger className="comparisonLedgerCard" entries={row.recordsB || []} title="Candidate B" /></div></div>)}</section></div> }
function CandidateColumn({ profile }) { return <section className="profileSummary"><p className="eyebrow ty-page-kicker">{profile.position}</p><h2 className="ty-section-title">{profile.fullName}</h2><KpiGrid profile={profile} compact /></section> }

export default function ComparisonPanel({ compareIds, onChange, onModalOpenChange, onSubmit, politicians, politiciansState, state }) {
  const [query, setQuery] = useState(''); const [jurisdictionFilter, setJurisdictionFilter] = useState('ALL'); const [isModalOpen, setIsModalOpen] = useState(false); const [page, setPage] = useState(1); const pageSize = 5
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); return politicians.filter((politician) => (jurisdictionFilter === 'ALL' || politician.jurisdiction === jurisdictionFilter) && (!q || politician.fullName.toLowerCase().includes(q) || (politician.position || '').toLowerCase().includes(q))) }, [jurisdictionFilter, politicians, query]); useEffect(() => setPage(1), [query, jurisdictionFilter]); useEffect(() => { onModalOpenChange?.(isModalOpen); return () => onModalOpenChange?.(false) }, [isModalOpen, onModalOpenChange]); const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize)); const safePage = Math.min(page, totalPages); const items = filtered.slice((safePage - 1) * pageSize, safePage * pageSize); const selectedA = politicians.find((politician) => politician.politicianId === compareIds.idA); const selectedB = politicians.find((politician) => politician.politicianId === compareIds.idB)
  async function submit(event) { const result = await onSubmit(event); if (result?.ok) setIsModalOpen(true) }
  return <section className="workspace compareWorkspace"><section className="compareFilterBar" aria-label="Candidate filters"><label>Search candidate<input name="candidateSearch" onChange={(event) => setQuery(event.target.value)} placeholder="Search by name or position" value={query} /></label><label>Jurisdiction<select value={jurisdictionFilter} onChange={(event) => setJurisdictionFilter(event.target.value)}><option value="ALL">All</option><option value="NATIONAL">National</option><option value="CEBU_CITY">Cebu City</option></select></label></section><StatusLine state={state} /><StatusLine state={politiciansState} /><div className="compareSelectionGrid">{['left', 'right'].map((side) => <section key={side} className={`compareColumn${side === 'right' ? ' right' : ''}`}><div className="compareColumnHeader"><p className="compareColumnTitle">Candidate {side === 'left' ? 'A' : 'B'}</p><PaginationMini page={safePage} totalPages={totalPages} onChange={setPage} /></div><div className="compareCardList">{items.map((politician) => { const selectedId = side === 'left' ? compareIds.idA : compareIds.idB; return <button className={selectedId === politician.politicianId ? 'compareCard selected' : 'compareCard'} key={`${side}-${politician.politicianId}`} onClick={() => onChange((current) => ({ ...current, [side === 'left' ? 'idA' : 'idB']: politician.politicianId }))} type="button"><span className="compareCardAvatar">{politician.profileImageUrl ? <img alt={politician.fullName} src={politician.profileImageUrl} /> : initialsFor(politician.fullName)}</span><span className="compareCardBody"><strong className="ty-card-title">{politician.fullName}</strong><small className="ty-meta">{formatPosition(politician.position)}</small><small className="ty-meta">{formatJurisdiction(politician.jurisdiction)}</small></span></button> })}</div></section>)}</div><form className="compareFloatingBar" onSubmit={submit}><div className="compareFloatingContent"><div className="compareCandidateSummary"><p className="ty-label">Candidate A</p><strong>{selectedA?.fullName || 'Not selected'}</strong></div><button disabled={state.status === 'loading' || !compareIds.idA || !compareIds.idB} type="submit" className="compareSubmitButton"><ScaleIcon size={18} /><span>{state.status === 'loading' ? 'Comparing...' : 'Compare Selected'}</span></button><div className="compareCandidateSummary right"><p className="ty-label">Candidate B</p><strong>{selectedB?.fullName || 'Not selected'}</strong></div></div></form>{isModalOpen && state.data && <div className="comparisonModalBackdrop" onClick={() => setIsModalOpen(false)}><section className="comparisonModal" onClick={(event) => event.stopPropagation()} role="dialog"><header className="comparisonModalHeader"><h2 className="ty-section-title">Comparison Result</h2><button type="button" onClick={() => setIsModalOpen(false)}>Close</button></header><div className="comparisonModalBody"><ComparisonGrid comparison={state.data} /></div></section></div>}</section>
}
