import { useEffect, useState } from 'react'
import LifecycleStageStrip from '../../components/LifecycleStageStrip'
import { ContributionCardsSkeleton } from '../../components/Skeletons'
import { formatActionIdentifier } from '../../components/governance/positionConfig'
import { formatActionMetric, formatDate, PaginationMini, StatusLine } from '../pageHelpers'

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8080'
async function readApiResponse(response) { const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message || `Request failed with status ${response.status}`); return body }
export default function MyContributionsPanel({ onNavigateToSubmit, user }) { const [contributions, setContributions] = useState([]); const [state, setState] = useState({ status: 'loading', message: 'Retrieving your contribution history...' }); const [page, setPage] = useState(1); useEffect(() => { if (!user?.userId) { setContributions([]); setState({ status: 'error', message: 'Unable to load contribution history without a user id.' }); return } fetch(`${API_BASE_URL}/api/submissions/contributor/${user.userId}`).then(readApiResponse).then((data) => { setContributions(Array.isArray(data) ? data : []); setState({ status: 'success', message: '' }) }).catch((error) => { setContributions([]); setState({ status: 'error', message: error.message }) }) }, [user?.userId]); const pageSize = 6; const totalPages = Math.max(1, Math.ceil(contributions.length / pageSize)); const safePage = Math.min(page, totalPages); const items = contributions.slice((safePage - 1) * pageSize, safePage * pageSize); useEffect(() => setPage(1), [contributions.length]); return <section className="workspace"><section className="dashboardHeaderBlock"><h2 className="ty-section-title">My Contributions</h2><p className="ty-body">Track the verification lifecycle of your submitted political records.</p><button type="button" onClick={() => onNavigateToSubmit?.()}>Submit Official Audit Record</button></section><StatusLine state={state} /><div className="myContribGrid">{state.status === 'loading' && <ContributionCardsSkeleton count={4} />}{state.status !== 'loading' && contributions.length === 0 && <div className="myContribEmpty"><p className="ty-body">No contributions yet. Head to <strong>File Evidence</strong> to submit your first record.</p></div>}{items.map((item) => <article key={item.submissionId} className="review-card"><div><span>#{item.submissionId.substring(0, 8).toUpperCase()}</span><span>{formatDate(item.createdAt)}</span></div><div className="review-cardFacts">{[['Category', item.categoryTag], ['Action Tag', formatActionIdentifier(item.actionIdentifier)], ['Metric', formatActionMetric(item.actionDetails, item.actionIdentifier)]].map(([label, value]) => <div key={label}><span className="ty-label">{label}</span><strong>{value}</strong></div>)}</div><p>"{item.impactSummary}"</p><div><span className="ty-label">Source</span> <a href={item.sourceUrl} target="_blank" rel="noreferrer">{item.sourceUrl}</a></div><LifecycleStageStrip status={item.status} title="Lifecycle Stage" /></article>)}</div>{contributions.length > pageSize && <div className="myContribPagination"><PaginationMini page={safePage} totalPages={totalPages} onChange={setPage} /></div>}</section> }
