import { useState } from 'react'
import ConfirmActionModal from '../../components/ConfirmActionModal'
import { BarChart3Icon, FolderIcon } from '../../components/icons/Lucide'
import { formatJurisdiction, formatPosition } from '../../components/governance/positionConfig'
import { KpiGrid, PageSectionLoader, ProfileSkeleton, StatusLine, TimelineLedger } from '../pageHelpers'

function initialsFor(name = '') {
  return name.split(' ').filter(Boolean).slice(0, 2).map((part) => part[0]).join('').toUpperCase() || 'P'
}

function exportLedger(entries, profile, type) {
  const data = type === 'json' ? JSON.stringify({ metadata: { politicianId: profile.politicianId, fullName: profile.fullName, exportedAt: new Date().toISOString() }, timelineEntries: entries }, null, 2) : [['Date', 'Category', 'Action Type', 'Summary', 'Source Citation', 'Status'], ...entries.map((entry) => [entry.createdAt ? new Date(entry.createdAt).toISOString().split('T')[0] : '', entry.categoryTag || '', entry.actionIdentifier || '', entry.summary || entry.impactSummary || '', entry.sourceUrl || '', entry.status || 'PUBLISHED'])].map((row) => row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(',')).join('\r\n')
  const url = URL.createObjectURL(new Blob([data], { type: type === 'json' ? 'application/json' : 'text/csv' })); const link = document.createElement('a'); link.href = url; link.download = `${(profile.fullName || 'politician').toLowerCase().replace(/[^a-z0-9]+/g, '_')}_records.${type === 'json' ? 'json' : 'csv'}`; link.click(); URL.revokeObjectURL(url)
}

export default function PoliticianProfilePage({ dbUser, onAddContribution, onAppealModalOpenChange, onAuthPrompt, onModalOpenChange, onPoliticianUpdate, onReload, onUserUpdate, politicianId, politicians, state, token, user }) {
  const fallbackProfile = politicians.find((politician) => politician.politicianId === politicianId); const profile = state.status === 'loading' ? null : state.data || fallbackProfile; const entries = state.data?.publishedTimelineLedger || state.data?.timeline || state.data?.entries || []; const [appealTarget, setAppealTarget] = useState(null); const [appealDetails, setAppealDetails] = useState(''); const [appealState, setAppealState] = useState({ status: 'idle', message: '' }); const isAdmin = dbUser?.role === 'ADMIN'
  async function confirmAppeal() { if (!appealTarget?.submissionId) return; setAppealState({ status: 'loading', message: 'Filing appeal...' }); try { const response = await fetch(`${import.meta.env.VITE_API_BASE_URL || 'http://localhost:8080'}/api/moderation/appeal`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ submissionId: appealTarget.submissionId, details: appealDetails.trim() }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Appeal failed'); onUserUpdate?.({ trustScore: data.trustScore }); setAppealState({ status: 'success', message: data.message || 'Appeal filed.' }); setAppealTarget(null); onAppealModalOpenChange?.(false) } catch (error) { setAppealState({ status: 'error', message: error.message }); setAppealTarget(null); onAppealModalOpenChange?.(false) } }
  if (!politicianId) return <section className="workspace"><p className="emptyState">Select a politician card first.</p></section>
  return <section className="workspace politicianProfileWorkspace"><StatusLine state={state} />{state.status === 'loading' && <PageSectionLoader />}{state.status === 'loading' && !profile && <ProfileSkeleton />}{profile && <><section className="politicianProfileHero"><div className="politicianProfilePortrait">{profile.profileImageUrl ? <img src={profile.profileImageUrl} alt={profile.fullName} /> : <span>{initialsFor(profile.fullName)}</span>}</div><div className="politicianProfileIdentity"><p className="eyebrow ty-page-kicker">{formatPosition(profile.position) || 'UNKNOWN POSITION'}</p><h1>{profile.fullName}</h1><div className="politicianProfileMeta"><span>{formatJurisdiction(profile.jurisdiction) || 'Unspecified jurisdiction'}</span><span>{profile.partyAffiliation || 'Party affiliation unavailable'}</span>{profile.termStart && profile.termEnd && <span>{new Date(profile.termStart).toLocaleDateString()} – {new Date(profile.termEnd).toLocaleDateString()}</span>}</div></div><div className="politicianProfileStatus"><span className="ty-label">Profile status</span><strong>{profile.status || 'ACTIVE'}</strong></div></section>{isAdmin && <div className="politicianProfileActions"><button type="button">Edit Profile</button><button type="button" onClick={() => user ? onAddContribution(profile.politicianId) : onAuthPrompt?.('propose')}>Add Contribution</button><button type="button" id="export-ledger-csv-btn" onClick={() => exportLedger(entries, profile, 'csv')}><BarChart3Icon size={16} /> Export CSV</button><button type="button" id="export-ledger-json-btn" onClick={() => exportLedger(entries, profile, 'json')}><FolderIcon size={16} /> Export JSON</button></div>}<KpiGrid profile={profile} /><div className="politicianProfileBody"><section className="biographyBlock"><p className="ty-page-kicker">About the official</p><h2 className="ty-section-title">Biography</h2><p className="ty-body">{profile.biography || 'No biography available.'}</p></section><section className="politicianProfileDetails"><p className="ty-page-kicker">Profile details</p><dl><div><dt>Position</dt><dd>{formatPosition(profile.position) || 'Not specified'}</dd></div><div><dt>Jurisdiction</dt><dd>{formatJurisdiction(profile.jurisdiction) || 'Not specified'}</dd></div><div><dt>Party</dt><dd>{profile.partyAffiliation || 'Not disclosed'}</dd></div></dl></section></div><StatusLine state={appealState} /><TimelineLedger entries={entries} isLoading={state.status === 'loading'} onAppeal={(entry) => { if (!entry?.submissionId) return; setAppealDetails(''); setAppealTarget(entry); onAppealModalOpenChange?.(true) }} onAuthPrompt={onAuthPrompt} title="Published Contribution Timeline" user={user} /></>}</section>
}
